### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by mucahitrtn** [wangjuncongyu/chromosome-instance-segmentation-dataset#2]
I recently tried to download the data from baidu but encountered an issue. The message displayed was "Registration from overseas and Hong Kong, Macao, and Taiwan regions is not currently supported." Due to this limitation, I am unable to access the data. Could you please consider providing the data through an alternative platform that is accessible internationally?

**Comment by wangjuncongyu** [comment]
you can try: https://drive.google.com/file/d/19iMkRteG0wyz45a4KAwQfWR6arYRzEbB/view?usp=sharing

---- Replied Message ----
| From | ***@***.***> |
| Date | 02/02/2024 18:03 |
| To | wangjuncongyu/chromosome-instance-segmentation-dataset ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [wangjuncongyu/chromosome-instance-segmentation-dataset] About the dataset (Issue #2) |

I recently tried to download data from baidu but encountered an issue. The message displayed was "Registration from overseas and Hong Kong, Macao, and Taiwan regions is not currently supported." Due to this limitation, I am unable to access the data. Could you please consider providing the data through an alternative platform that is accessible internationally?

**Comment by mucahitrtn** [comment]
Thank you.
